FROM rust:1.90.0

ENV SRC_APP_DIR="/usr/src/app"

WORKDIR ${SRC_APP_DIR}

COPY ./Cargo.toml .
COPY ./Cargo.lock .

COPY ./api ./api
COPY ./fastq_service ./fastq_service
COPY ./shared ./shared

RUN cargo build --release -p api && mv ./target/release/api /usr/local/bin/api

EXPOSE 8001
ENTRYPOINT ["/usr/local/bin/api"]