services:
  api:
    ports:
      - "8001:8001"
    build:
      context: "../services"
      dockerfile: "Dockerfile.api"
    depends_on:
      - db
      - minio
      - nats
    env_file:
      - ../.env