services:
  app:
    container_name: dioxus-app
    ports:
      - "8080:8080"
    build:
      context: ../services
      dockerfile: app/Dockerfile
    env_file:
      - ../.env
    environment:
      - PORT=8080
      - IP=0.0.0.0
      - ENVIRONMENT=production
    depends_on:
      - db
    restart: unless-stopped
